baseURL = "https://www.rustcakes.com/"
languageCode = "en-us"
title = "rÅ¯stcakes"

[Params]
description = "Dessert Shop b e r l i n ğ”Ÿğ”¬ğ”©ğ”¡, ğ”¢ğ”¡ğ”¤ğ”¶, ğ”°ğ”´ğ”¢ğ”¢ğ”±, ğ”«ğ”ğ”±ğ”²ğ”¯ğ”ğ”©"
instagram = "https://www.instagram.com/rustcakes/"
socialImage = "img/B94bJCNJV-E.jpg"
