baseURL = "https://rustcakes-com.netlify.com/"
languageCode = "en-us"
title = "rÅ¯stcakes"
canonifyURLs = true

[Params]
description = "Dessert Shop b e r l i n ğ”Ÿğ”¬ğ”©ğ”¡, ğ”¢ğ”¡ğ”¤ğ”¶, ğ”°ğ”´ğ”¢ğ”¢ğ”±, ğ”«ğ”ğ”±ğ”²ğ”¯ğ”ğ”©"
instagram = "https://www.instagram.com/rustcakes/"
